Repository web3phl/directory, pull requests merged in 2022-07, with the labels that each got.

#2 Add tailwind config
  package.json
  postcss.config.js
  styles/globals.css
  tailwind.config.js
  yarn.lock
Labels: tweak

#5 fix: global css import error
  src/styles/Home.module.css
  src/styles/globals.css
Labels: fix

#3 🚀 RELEASE: v0.1.0 Alpha
  .eslintignore
  .eslintrc.json
  .github/ISSUE_TEMPLATE/bug.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature.yml
  .prettierignore
  .prettierrc
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  README.md
  SECURITY.md
  next.config.js
  package.json
  pages/_app.tsx
  pages/index.tsx
  postcss.config.js
  public/favicon.ico
  public/favicon/android-icon-144x144.png
  public/favicon/android-icon-192x192.png
  public/favicon/android-icon-36x36.png
  public/favicon/android-icon-48x48.png
  public/favicon/android-icon-72x72.png
  public/favicon/android-icon-96x96.png
  public/favicon/apple-icon-114x114.png
  public/favicon/apple-icon-120x120.png
  public/favicon/apple-icon-144x144.png
  public/favicon/apple-icon-152x152.png
  public/favicon/apple-icon-180x180.png
  public/favicon/apple-icon-57x57.png
  public/favicon/apple-icon-60x60.png
  public/favicon/apple-icon-72x72.png
  public/favicon/apple-icon-76x76.png
  public/favicon/apple-icon-precomposed.png
  public/favicon/apple-icon.png
  public/favicon/browserconfig.xml
  public/favicon/favicon-16x16.png
  public/favicon/favicon-32x32.png
  public/favicon/favicon-96x96.png
  public/favicon/favicon.ico
  public/favicon/manifest.json
  public/favicon/ms-icon-144x144.png
  public/favicon/ms-icon-150x150.png
  public/favicon/ms-icon-310x310.png
  public/favicon/ms-icon-70x70.png
  public/vercel.svg
  src/components/Seo.tsx
  src/pages/_app.tsx
  src/pages/_document.tsx
  src/pages/api/hello.ts
  src/pages/index.tsx
  src/styles/Home.module.css
  src/styles/globals.css
  tailwind.config.js
  tsconfig.json
  yarn.lock
Labels: chore, in progress, maintainers only, release

#11 🐛 FIX: removed empty content on tailwind config
  tailwind.config.js
Labels: fix

#15 fixed build error on dev
  src/components/Card.tsx
  src/pages/index.tsx
Labels: fix, in progress

#16 📦 NEW: add page for project info
  src/components/Card.tsx
  src/mock/index.ts
  src/pages/directory/[id].tsx
  src/pages/index.tsx
Labels: chore, feature, in review, waiting response

#18 📦 NEW: add react-query for data-management
  .eslintrc.json
  package.json
  src/components/Card.tsx
  src/components/Seo.tsx
  src/interface/index.ts
  src/mock/index.ts
  src/pages/_app.tsx
  src/pages/directory/[id].tsx
  src/pages/index.tsx
  src/queries/index.ts
  yarn.lock
Labels: feature, in progress, in review, tweak

#13 🚀 RELEASE: v1.0.0-alpha
  .eslintrc.json
  package.json
  prettier.config.js
  public/check.png
  public/verified.png
  src/components/Card.tsx
  src/components/Seo.tsx
  src/interface/index.ts
  src/mock/index.ts
  src/pages/_app.tsx
  src/pages/directory/[id].tsx
  src/pages/index.tsx
  src/queries/index.ts
  src/styles/Home.module.css
  src/styles/globals.css
  tailwind.config.js
  yarn.lock
Labels: chore, in progress, maintainers only, release, tweak
