Repository web3phl/directory, pull requests merged in 2022-08, with the labels that each got.

#20 🚀 RELEASE: v1.0.0 Update
  .gitignore
  public/placeholder.png
  src/components/Card.tsx
  src/interface/index.ts
  src/mock/index.ts
  src/pages/directory/[id].tsx
  src/pages/index.tsx
  src/queries/index.ts
  src/styles/globals.css
Labels: chore, feature, fix, maintainers only, release, tweak

#22 🚀 RELEASE: v1.0.1 Update
  src/constants.ts
  src/interface/index.ts
  src/pages/index.tsx
  src/queries/index.ts
Labels: chore, in progress, maintainers only, tweak

#27 ✨ TWEAK: UI revamp
  package.json
  public/purple-mesh.jpeg
  src/components/Card.tsx
  src/pages/_document.tsx
  src/pages/index.tsx
  tailwind.config.js
  yarn.lock
Labels: chore, fix, tweak

#31 HOTFIX: Card Tag UI
  src/components/Card.tsx
Labels: chore, fix

#28 🚀 RELEASE: v1.1.0 Update
  package.json
  public/purple-mesh.jpeg
  src/components/Card.tsx
  src/pages/_document.tsx
  src/pages/index.tsx
  tailwind.config.js
  yarn.lock
Labels: chore, fix, in progress, maintainers only, release, tweak

#33 ✨ TWEAK: ui fixes and code cleanup
  src/components/Card.tsx
  src/pages/index.tsx
  tailwind.config.js
Labels: chore, tweak

#50 🐛 FIX: capitalize site name
  src/pages/index.tsx
Labels: chore, fix

#60 Add Release Version + Removed Emojis
  src/pages/index.tsx
Labels: feature, tweak

#61 Added lastUpdated in API + Added Last Updated in UI
  src/pages/index.tsx
  src/queries/index.ts
  tailwind.config.js
Labels: feature, tweak
